### ISSUE TITLE
Contact for future projects

### ISSUE THREAD

**Issue by FWAJL** [FWM-Team/FWM-Backlog-Issues#16]
@damirius @gsouvik 

Since Brian's project is being put on hold soon, I would like to get your direct contact. You have shown quite the skills working on this framework I've built from scratch. You have provided a quality code and work from the start.

**_Therefore, I'd very likely work with you both in a heartbeat.**_

I am on [LinkedIn](https://www.google.fr/url?sa=t&rct=j&q=&esrc=s&source=web&cd=6&ved=0CDUQFjAF&url=https%3A%2F%2Ffr.linkedin.com%2Fpub%2Fj%25C3%25A9r%25C3%25A9mie-litzler%2F29%2F28a%2F535&ei=QEtsVatui6pRwpGB2Aw&usg=AFQjCNGusGpkvueVaR3Ig25OEGGZ45ho_A&sig2=N_m2rKqgHvxF5QOGhHxC1A&bvm=bv.94455598,d.d24&cad=rja). Could you add me in your connection? I will add this project to my list and you will be referenced if you don't tell me otherwise.

Finally, you can write to me on contact@jeremielitzler.net.

Thank you :+1:

**Comment by WebDevJL** [comment]
@damirius please send me your email contact. I may have a project where I will need your assistance.

Thanks.
