### ISSUE TITLE
Branch management

### ISSUE THREAD

**Issue by FWAJL** [FWM-Team/FWM-Backlog-Issues#9]
@FWM-Team/owners 

Can we delete the mapping and popup feature branches since you are all working on your dedicated branch?

Thank you.

**Comment by gsouvik** [comment]
@FWAJL 
Yes please, I'm no longer working on "feature_popup".

**Comment by damirius** [comment]
@FWAJL

I've added that code lost in the merge for Mapping Milestone E on the mapping branch, so when it's all done with merging and testing and the Mapping Milestone issues become closed you can remove it since I'll use other one.
Thanks

**Comment by bsaiken** [comment]
@FWAJL 
I agree with Damir and Souvik.
